/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.audit.model.impl;

import com.liferay.audit.model.AuditEntry;
import com.liferay.audit.model.AuditEntryModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AuditEntry service. Represents a row in the &quot;AUDIT_AuditEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AuditEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEntryImpl
 * @generated
 */
public class AuditEntryModelImpl
	extends BaseModelImpl<AuditEntry> implements AuditEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a audit entry model instance should use the <code>AuditEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "AUDIT_AuditEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"auditEntryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"entityName", Types.VARCHAR}, {"entityId", Types.BIGINT},
		{"action", Types.VARCHAR}, {"fieldName", Types.VARCHAR},
		{"oldValue", Types.VARCHAR}, {"newValue", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("auditEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("entityName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("action", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fieldName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oldValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("newValue", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AUDIT_AuditEntry (uuid_ VARCHAR(75) null,auditEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,entityName VARCHAR(75) null,entityId LONG,action VARCHAR(75) null,fieldName VARCHAR(75) null,oldValue VARCHAR(75) null,newValue VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table AUDIT_AuditEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY auditEntry.auditEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AUDIT_AuditEntry.auditEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AUDITENTRYID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AuditEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _auditEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _auditEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AuditEntry.class;
	}

	@Override
	public String getModelClassName() {
		return AuditEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AuditEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AuditEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuditEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((AuditEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AuditEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AuditEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AuditEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AuditEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AuditEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AuditEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AuditEntry, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<AuditEntry, Object>>();

			attributeGetterFunctions.put("uuid", AuditEntry::getUuid);
			attributeGetterFunctions.put(
				"auditEntryId", AuditEntry::getAuditEntryId);
			attributeGetterFunctions.put("groupId", AuditEntry::getGroupId);
			attributeGetterFunctions.put("companyId", AuditEntry::getCompanyId);
			attributeGetterFunctions.put("userId", AuditEntry::getUserId);
			attributeGetterFunctions.put("userName", AuditEntry::getUserName);
			attributeGetterFunctions.put(
				"createDate", AuditEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AuditEntry::getModifiedDate);
			attributeGetterFunctions.put(
				"entityName", AuditEntry::getEntityName);
			attributeGetterFunctions.put("entityId", AuditEntry::getEntityId);
			attributeGetterFunctions.put("action", AuditEntry::getAction);
			attributeGetterFunctions.put("fieldName", AuditEntry::getFieldName);
			attributeGetterFunctions.put("oldValue", AuditEntry::getOldValue);
			attributeGetterFunctions.put("newValue", AuditEntry::getNewValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AuditEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AuditEntry, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AuditEntry, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<AuditEntry, String>)AuditEntry::setUuid);
			attributeSetterBiConsumers.put(
				"auditEntryId",
				(BiConsumer<AuditEntry, Long>)AuditEntry::setAuditEntryId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AuditEntry, Long>)AuditEntry::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AuditEntry, Long>)AuditEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<AuditEntry, Long>)AuditEntry::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<AuditEntry, String>)AuditEntry::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AuditEntry, Date>)AuditEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AuditEntry, Date>)AuditEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"entityName",
				(BiConsumer<AuditEntry, String>)AuditEntry::setEntityName);
			attributeSetterBiConsumers.put(
				"entityId",
				(BiConsumer<AuditEntry, Long>)AuditEntry::setEntityId);
			attributeSetterBiConsumers.put(
				"action",
				(BiConsumer<AuditEntry, String>)AuditEntry::setAction);
			attributeSetterBiConsumers.put(
				"fieldName",
				(BiConsumer<AuditEntry, String>)AuditEntry::setFieldName);
			attributeSetterBiConsumers.put(
				"oldValue",
				(BiConsumer<AuditEntry, String>)AuditEntry::setOldValue);
			attributeSetterBiConsumers.put(
				"newValue",
				(BiConsumer<AuditEntry, String>)AuditEntry::setNewValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getAuditEntryId() {
		return _auditEntryId;
	}

	@Override
	public void setAuditEntryId(long auditEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_auditEntryId = auditEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getEntityName() {
		if (_entityName == null) {
			return "";
		}
		else {
			return _entityName;
		}
	}

	@Override
	public void setEntityName(String entityName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityName = entityName;
	}

	@Override
	public long getEntityId() {
		return _entityId;
	}

	@Override
	public void setEntityId(long entityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityId = entityId;
	}

	@Override
	public String getAction() {
		if (_action == null) {
			return "";
		}
		else {
			return _action;
		}
	}

	@Override
	public void setAction(String action) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_action = action;
	}

	@Override
	public String getFieldName() {
		if (_fieldName == null) {
			return "";
		}
		else {
			return _fieldName;
		}
	}

	@Override
	public void setFieldName(String fieldName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fieldName = fieldName;
	}

	@Override
	public String getOldValue() {
		if (_oldValue == null) {
			return "";
		}
		else {
			return _oldValue;
		}
	}

	@Override
	public void setOldValue(String oldValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oldValue = oldValue;
	}

	@Override
	public String getNewValue() {
		if (_newValue == null) {
			return "";
		}
		else {
			return _newValue;
		}
	}

	@Override
	public void setNewValue(String newValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_newValue = newValue;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AuditEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AuditEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AuditEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AuditEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AuditEntryImpl auditEntryImpl = new AuditEntryImpl();

		auditEntryImpl.setUuid(getUuid());
		auditEntryImpl.setAuditEntryId(getAuditEntryId());
		auditEntryImpl.setGroupId(getGroupId());
		auditEntryImpl.setCompanyId(getCompanyId());
		auditEntryImpl.setUserId(getUserId());
		auditEntryImpl.setUserName(getUserName());
		auditEntryImpl.setCreateDate(getCreateDate());
		auditEntryImpl.setModifiedDate(getModifiedDate());
		auditEntryImpl.setEntityName(getEntityName());
		auditEntryImpl.setEntityId(getEntityId());
		auditEntryImpl.setAction(getAction());
		auditEntryImpl.setFieldName(getFieldName());
		auditEntryImpl.setOldValue(getOldValue());
		auditEntryImpl.setNewValue(getNewValue());

		auditEntryImpl.resetOriginalValues();

		return auditEntryImpl;
	}

	@Override
	public AuditEntry cloneWithOriginalValues() {
		AuditEntryImpl auditEntryImpl = new AuditEntryImpl();

		auditEntryImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		auditEntryImpl.setAuditEntryId(
			this.<Long>getColumnOriginalValue("auditEntryId"));
		auditEntryImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		auditEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		auditEntryImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		auditEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		auditEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		auditEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		auditEntryImpl.setEntityName(
			this.<String>getColumnOriginalValue("entityName"));
		auditEntryImpl.setEntityId(
			this.<Long>getColumnOriginalValue("entityId"));
		auditEntryImpl.setAction(this.<String>getColumnOriginalValue("action"));
		auditEntryImpl.setFieldName(
			this.<String>getColumnOriginalValue("fieldName"));
		auditEntryImpl.setOldValue(
			this.<String>getColumnOriginalValue("oldValue"));
		auditEntryImpl.setNewValue(
			this.<String>getColumnOriginalValue("newValue"));

		return auditEntryImpl;
	}

	@Override
	public int compareTo(AuditEntry auditEntry) {
		long primaryKey = auditEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AuditEntry)) {
			return false;
		}

		AuditEntry auditEntry = (AuditEntry)object;

		long primaryKey = auditEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AuditEntry> toCacheModel() {
		AuditEntryCacheModel auditEntryCacheModel = new AuditEntryCacheModel();

		auditEntryCacheModel.uuid = getUuid();

		String uuid = auditEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			auditEntryCacheModel.uuid = null;
		}

		auditEntryCacheModel.auditEntryId = getAuditEntryId();

		auditEntryCacheModel.groupId = getGroupId();

		auditEntryCacheModel.companyId = getCompanyId();

		auditEntryCacheModel.userId = getUserId();

		auditEntryCacheModel.userName = getUserName();

		String userName = auditEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			auditEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			auditEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			auditEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			auditEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			auditEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		auditEntryCacheModel.entityName = getEntityName();

		String entityName = auditEntryCacheModel.entityName;

		if ((entityName != null) && (entityName.length() == 0)) {
			auditEntryCacheModel.entityName = null;
		}

		auditEntryCacheModel.entityId = getEntityId();

		auditEntryCacheModel.action = getAction();

		String action = auditEntryCacheModel.action;

		if ((action != null) && (action.length() == 0)) {
			auditEntryCacheModel.action = null;
		}

		auditEntryCacheModel.fieldName = getFieldName();

		String fieldName = auditEntryCacheModel.fieldName;

		if ((fieldName != null) && (fieldName.length() == 0)) {
			auditEntryCacheModel.fieldName = null;
		}

		auditEntryCacheModel.oldValue = getOldValue();

		String oldValue = auditEntryCacheModel.oldValue;

		if ((oldValue != null) && (oldValue.length() == 0)) {
			auditEntryCacheModel.oldValue = null;
		}

		auditEntryCacheModel.newValue = getNewValue();

		String newValue = auditEntryCacheModel.newValue;

		if ((newValue != null) && (newValue.length() == 0)) {
			auditEntryCacheModel.newValue = null;
		}

		return auditEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AuditEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AuditEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuditEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AuditEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AuditEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AuditEntry.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _auditEntryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _entityName;
	private long _entityId;
	private String _action;
	private String _fieldName;
	private String _oldValue;
	private String _newValue;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AuditEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AuditEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("auditEntryId", _auditEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("entityName", _entityName);
		_columnOriginalValues.put("entityId", _entityId);
		_columnOriginalValues.put("action", _action);
		_columnOriginalValues.put("fieldName", _fieldName);
		_columnOriginalValues.put("oldValue", _oldValue);
		_columnOriginalValues.put("newValue", _newValue);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("auditEntryId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("entityName", 256L);

		columnBitmasks.put("entityId", 512L);

		columnBitmasks.put("action", 1024L);

		columnBitmasks.put("fieldName", 2048L);

		columnBitmasks.put("oldValue", 4096L);

		columnBitmasks.put("newValue", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AuditEntry _escapedModel;

}