/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.audit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AuditEntry service. Represents a row in the &quot;AUDIT_AuditEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.audit.model.impl.AuditEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.audit.model.impl.AuditEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEntry
 * @generated
 */
@ProviderType
public interface AuditEntryModel
	extends BaseModel<AuditEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audit entry model instance should use the {@link AuditEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this audit entry.
	 *
	 * @return the primary key of this audit entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audit entry.
	 *
	 * @param primaryKey the primary key of this audit entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this audit entry.
	 *
	 * @return the uuid of this audit entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this audit entry.
	 *
	 * @param uuid the uuid of this audit entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the audit entry ID of this audit entry.
	 *
	 * @return the audit entry ID of this audit entry
	 */
	public long getAuditEntryId();

	/**
	 * Sets the audit entry ID of this audit entry.
	 *
	 * @param auditEntryId the audit entry ID of this audit entry
	 */
	public void setAuditEntryId(long auditEntryId);

	/**
	 * Returns the group ID of this audit entry.
	 *
	 * @return the group ID of this audit entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this audit entry.
	 *
	 * @param groupId the group ID of this audit entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this audit entry.
	 *
	 * @return the company ID of this audit entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this audit entry.
	 *
	 * @param companyId the company ID of this audit entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this audit entry.
	 *
	 * @return the user ID of this audit entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this audit entry.
	 *
	 * @param userId the user ID of this audit entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this audit entry.
	 *
	 * @return the user uuid of this audit entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this audit entry.
	 *
	 * @param userUuid the user uuid of this audit entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this audit entry.
	 *
	 * @return the user name of this audit entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this audit entry.
	 *
	 * @param userName the user name of this audit entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this audit entry.
	 *
	 * @return the create date of this audit entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this audit entry.
	 *
	 * @param createDate the create date of this audit entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this audit entry.
	 *
	 * @return the modified date of this audit entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this audit entry.
	 *
	 * @param modifiedDate the modified date of this audit entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the entity name of this audit entry.
	 *
	 * @return the entity name of this audit entry
	 */
	@AutoEscape
	public String getEntityName();

	/**
	 * Sets the entity name of this audit entry.
	 *
	 * @param entityName the entity name of this audit entry
	 */
	public void setEntityName(String entityName);

	/**
	 * Returns the entity ID of this audit entry.
	 *
	 * @return the entity ID of this audit entry
	 */
	public long getEntityId();

	/**
	 * Sets the entity ID of this audit entry.
	 *
	 * @param entityId the entity ID of this audit entry
	 */
	public void setEntityId(long entityId);

	/**
	 * Returns the action of this audit entry.
	 *
	 * @return the action of this audit entry
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this audit entry.
	 *
	 * @param action the action of this audit entry
	 */
	public void setAction(String action);

	/**
	 * Returns the field name of this audit entry.
	 *
	 * @return the field name of this audit entry
	 */
	@AutoEscape
	public String getFieldName();

	/**
	 * Sets the field name of this audit entry.
	 *
	 * @param fieldName the field name of this audit entry
	 */
	public void setFieldName(String fieldName);

	/**
	 * Returns the old value of this audit entry.
	 *
	 * @return the old value of this audit entry
	 */
	@AutoEscape
	public String getOldValue();

	/**
	 * Sets the old value of this audit entry.
	 *
	 * @param oldValue the old value of this audit entry
	 */
	public void setOldValue(String oldValue);

	/**
	 * Returns the new value of this audit entry.
	 *
	 * @return the new value of this audit entry
	 */
	@AutoEscape
	public String getNewValue();

	/**
	 * Sets the new value of this audit entry.
	 *
	 * @param newValue the new value of this audit entry
	 */
	public void setNewValue(String newValue);

	@Override
	public AuditEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}